<a href="https://colab.research.google.com/github/songseokbeom/ML_study/blob/master/Data_Mining/DM_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# #Problem 1 (10 pts)
'Hello, world!' 문장을 출력하는 cell을 작성하시오.

In [0]:
### Put your code here ##########
print('Hello, world!')
#################################

Hello, world!


# #Problem 2 (10 pts)
P2_list의 원소 1과 2 사이에 string 'abc'를 추가하시오.

In [0]:
P2_list = [1, 2, 3, 4, 5]

### Put your code here ##########
P2_list.insert(1, 'abc')
#################################

print(P2_list)

[1, 'abc', 2, 3, 4, 5]


# #Problem 3 (10 pts)
list [1, 2, 3]과 list [4, 5, 6]을 합쳐 [1, 2, 3, 4, 5, 6] list를 만드시오.

In [0]:
P3_list_1 = [1, 2, 3]
P3_list_2 = [4, 5, 6]
P3_list_concat = None

### Put your code here ##########
P3_list_concat = P3_list_1 + P3_list_2
#################################

print(P3_list_concat)

[1, 2, 3, 4, 5, 6]


# #Problem 4 (10 pts)
2차원 numpy array에서 첫번째 column에 있는 값들을 1차원 numpy array 형태로 P4 변수에 저장하시오. (for문 사용 금지)

In [0]:
import numpy as np
P4_array = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
P4 = None

### Put your code here ##########
P4 = P4_array[:, 0]
#################################

print(P4)

[1 4 7]


# #Problem 5 (30 pts)
원소가 3개인 벡터가 두개 이상 담겨있는 numpy array를 input으로 받아, target 벡터 [1, 2, 3]과의 L2 distance가 큰 순서대로 벡터들을 내림차순 정렬하여 출력해주는 함수를 작성하시오.
- for문 사용 금지
- ex) input : [[1,2,3],[2,5,10],[2,4,3],[1,2,4]], output : [[2,5,10],[2,4,3],[1,2,4],[1,2,3]]
- numpy의 broadcasting, shape, axis 개념, numpy의 다양한 연산 메소드들을 구글에 충분히 검색해볼 것.

In [0]:
def Problem_5(input_arr):
    target_vector = np.array([1, 2, 3])
    sorted_arr = None
    
    ### Put your code here ##########
    sorted_arr = np.subtract(input_arr, target_vector)
    sorted_arr = np.sum(sorted_arr**2, axis=1)
    sorted_arr = input_arr[np.argsort(sorted_arr)[::-1]]
    #################################
    
    return sorted_arr

test_arr = np.array([[1,2,3],
                     [2,5,10],
                     [2,4,3],
                     [1,2,4]])
print(Problem_5(test_arr))

[[ 2  5 10]
 [ 2  4  3]
 [ 1  2  4]
 [ 1  2  3]]


# #Problem 6 (30 pts)
2차원 input array와 index array를 입력으로 받아, i번째 원소가 input array의 (i, index_array[i])번째 값인 1차원 numpy array를 출력하는 함수를 작성하시오.
- for문 사용 금지
- ex) input : [[1,2,3],[2,5,10],[2,4,3],[1,2,4]], [0,1,1,2], output : [1,5,4,4]

In [0]:
def Problem_6(input_arr, index_arr):
    output_arr = None
    
    ### Put your code here ##########
    a = index_arr.shape[0]
    output_arr = input_arr[np.arange(a), index_arr]
    #################################
    
    return output_arr

test_arr = np.array([[1,2,3],
                     [2,5,10],
                     [2,4,3],
                     [1,2,4]])
test_index = np.array([0,1,1,2])
print(Problem_6(test_arr, test_index))

[1 5 4 4]
